### ISSUE TITLE
What is the real use case of shkd?

### ISSUE THREAD

**Issue by alexherbo2** [baskerville/shkd#3]

**Comment by bi4k8** [comment]
Right now there are essentially three disjoint "universes" for input handling on Linux, all built on top of the same kernel infrastructure. The first is the console, where alt-f#/alt-left/alt-right will change VT. There's no way to configure other hotkeys in the console, though you can configure individual applications which may be reading from the TTY in raw mode, e.g. line editors like readline.

The second is X11, where any program that wants to bind keys has to deal with the travails of event masks, implicit and explicit grabs, the send_event flag, and so on. There may be ways to get around these limitations with XTest or another protocol, but it's really messy and virtually impossible to get right. For example, try to generate a keypress for another program from the command clause of a binding in XBindKeys. Rather than being an implementation detail in XBindKeys, the difficulty really stems from X's poorly-designed input paradigm.

The third is Wayland, where every compositor can actually do something completely different. Some compositors support (various method for defining) user-specified keybindings to launch applications or control windows, but they do not share a configuration format, semantics, or a common level of expressiveness. Eventually, it's likely that a Wayland protocol will be standardized for applications to register global hotkeys or actions which the user and compositor can work together to map to an actual sequence of input events, transparently to the application, but this is still a ways off. In any event, key configuration of compositors is spotty and non-portable.

shkd provides a way to bind actions to the raw input events produced by the Linux kernel and have the same behavior in all of these three universes. The downside is that it isn't able to ensure mutual exclusion (each event processed by one application) because the kernel event nodes work in a broadcast fashion, and it isn't possible to retroactively hide events you want to process from the other programs that you don't want to process said event. The *right* way to solve that problem is to build a coherent environment from the bottom up, ideally on top of Wayland, but in the meantime shkd is very useful.
